---
- hosts: localhost
  tasks:
  - name: Install PHP
    yum: name=php
    become: yes

  - name: Install PHP-MySQL
    yum: name=php-mysql
    become: yes

  - name: Install PHP-MySQL
    yum: name=mysql
    become: yes

  - name: Install PHP-MySQL
    yum: name=httpd
    become: yes

  - name: Download WordPress
    get_url: url=https://wordpress.org/latest.tar.gz dest=/tmp/wordpress.tar.gz validate_certs=no
    become: yes

  - name: Unzip WordPress
    unarchive: src=/tmp/wordpress.tar.gz dest=/var/www/html copy=no
    become: yes

  - name: Create wp-config.php from sample
    copy:
      src: /var/www/html/wordpress/wp-config-sample.php
      dest: /var/www/html/wordpress/wp-config.php
    become: yes

  - name: Add database name to the wp-config.php
    replace:
      path: /var/www/html/wordpress/wp-config.php
      regexp: 'database_name_here'
      replace: "{{ lookup('env','DB_NAME') }}"
    become: yes
 
  - name: Add database name to the wp-config.php
    replace:
      path: /var/www/html/wordpress/wp-config.php
      regexp: 'database_name_here'
      replace: "{{ lookup('env','DB_USER') }}"
    become: yes

  - name: Add database name to the wp-config.php
    replace:
      path: /var/www/html/wordpress/wp-config.php
      regexp: 'database_name_here'
      replace: "{{ lookup('env','DB_PASSWORD') }}"
    become: yes

  - name: Add database name to the wp-config.php
    replace:
      path: /var/www/html/wordpress/wp-config.php
      regexp: 'database_name_here'
      replace: "{{ lookup('env','DB_INSTANCE') }}"
    become: yes

  - name: Set file permission of wp-config.php
    file:
      path: /var/www/html/wordpress/wp-config.php
      owner: root
      group: root
      mode: 000500
    become: yes

  - name: Start service httpd, if not started
    service:
      name: httpd
      state: started
    become: yes
    
